Count,Message,Traceback,Nodes
1274,list index out of range,"  File ""/Users/maruf_maruf1/anaconda3/envs/myenv/lib/python3.10/site-packages/locust/user/task.py"", line 319, in run
    self.execute_next_task()
  File ""/Users/maruf_maruf1/anaconda3/envs/myenv/lib/python3.10/site-packages/locust/user/task.py"", line 344, in execute_next_task
    self.execute_task(self._task_queue.pop(0))
  File ""/Users/maruf_maruf1/anaconda3/envs/myenv/lib/python3.10/site-packages/locust/user/task.py"", line 457, in execute_task
    task(self.user)
  File ""/Users/maruf_maruf1/Library/CloudStorage/OneDrive-BaylorUniversity/RA/pptam/pptam-tool/toolchain/executed/train-ticket/locustfile.py"", line 194, in perform_task
    requests.perform_task(""book"")
  File ""/Users/maruf_maruf1/Library/CloudStorage/OneDrive-BaylorUniversity/RA/pptam/pptam-tool/toolchain/executed/train-ticket/locustfile.py"", line 155, in perform_task
    task()
  File ""/Users/maruf_maruf1/Library/CloudStorage/OneDrive-BaylorUniversity/RA/pptam/pptam-tool/toolchain/executed/train-ticket/locustfile.py"", line 131, in book
    self.order_id = response_as_json[0][""id""]
",local
